"use strict";
exports.__esModule = true;
exports.WorkItem = exports.Work = exports.Services = exports.Navbar = exports.Home = exports.Contact = exports.Button = exports.About = void 0;
var About_1 = require("./About");
exports.About = About_1["default"];
var Button_1 = require("./Button");
exports.Button = Button_1["default"];
var Contact_1 = require("./Contact");
exports.Contact = Contact_1["default"];
var Home_1 = require("./Home");
exports.Home = Home_1["default"];
var Navbar_1 = require("./Navbar");
exports.Navbar = Navbar_1["default"];
var Services_1 = require("./Services");
exports.Services = Services_1["default"];
var Work_1 = require("./Work");
exports.Work = Work_1["default"];
var WorkItem_1 = require("./WorkItem");
exports.WorkItem = WorkItem_1["default"];
